### ISSUE TITLE
ClassNotFoundException at start the app

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/flyve-mdm-android-dashboard#32]
This error is showing on API 16 to 19

```
W/dalvikvm( 3937): threadid=1: thread exiting with uncaught exception (group=0x418d6ce0)
E/AndroidRuntime( 3937): FATAL EXCEPTION: main
E/AndroidRuntime( 3937): Process: org.flyve.admin.dashboard, PID: 3937
E/AndroidRuntime( 3937): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.flyve.admin.dashboard/org.flyve.admin.dashboard.SplashActivity}: java.lang.ClassNotFoundException: Didn't find class "org.flyve.admin.dashboard.SplashActivity" on path: DexPathList[[zip file "/data/app/org.flyve.admin.dashboard-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.flyve.admin.dashboard-2, /vendor/lib, /system/lib]]
E/AndroidRuntime( 3937): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2131)
E/AndroidRuntime( 3937): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
E/AndroidRuntime( 3937): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime( 3937): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
E/AndroidRuntime( 3937): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3937): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3937): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime( 3937): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3937): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3937): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime( 3937): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime( 3937): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 3937): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.flyve.admin.dashboard.SplashActivity" on path: DexPathList[[zip file "/data/app/org.flyve.admin.dashboard-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.flyve.admin.dashboard-2, /vendor/lib, /system/lib]]
E/AndroidRuntime( 3937): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 3937): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime( 3937): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime( 3937): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
E/AndroidRuntime( 3937): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2122)
E/AndroidRuntime( 3937): 	... 11 more
W/ActivityManager( 2270):   Force finishing activity org.flyve.admin.dashboard/.SplashActivity
W/ActivityManager( 2270): Activity pause timeout for ActivityRecord{41dd2bb0 u0 org.flyve.admin.dashboard/.SplashActivity t2 f}
I/Timeline( 2576): Timeline: Activity_idle id: android.os.BinderProxy@41d37f70 time:48527
I/ActivityManager( 2270): Killing 3532:android.process.acore/u0a4 (adj 15): empty #17
I/Timeline( 2270): Timeline: Activity_windows_visible id: ActivityRecord{41ddc000 u0 com.cyanogenmod.trebuchet/org.cyanogenmod.trebuchet.CustomHomeLauncher t1} time:48942
```

**Comment by rafaelje** [comment]
In some cases this error gets because all the news android libraries got more functions and are greater than the size limit of 64K can be solved with:

add this compile on app gradle
`compile 'com.android.support:multidex:1.0.2'`

add this script on Application file
```
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }
```
